#!/usr/bin/env node
/**
 * Waits for .devdeck/daemon.json (written by the daemon), syncs Next env, picks a free UI port, runs next dev.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { spawn } from "node:child_process";
import net from "node:net";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { setTimeout as delay } from "node:timers/promises";

const pkgRoot = dirname(fileURLToPath(import.meta.url));

function resolveProjectRoot() {
  let dir = pkgRoot;
  for (let i = 0; i < 20; i++) {
    if (existsSync(join(dir, "devdeck.config.ts"))) return dir;
    if (existsSync(join(dir, "pnpm-workspace.yaml"))) return dir;
    const p = dirname(dir);
    if (p === dir) break;
    dir = p;
  }
  return dirname(pkgRoot);
}

async function waitDaemonMeta(projectRoot) {
  const p = join(projectRoot, ".devdeck", "daemon.json");
  for (let i = 0; i < 75; i++) {
    if (existsSync(p)) {
      try {
        return JSON.parse(readFileSync(p, "utf8"));
      } catch {
        /* retry */
      }
    }
    await delay(200);
  }
  return null;
}

function portFree(port) {
  return new Promise((resolve) => {
    const s = net.createServer();
    s.once("error", () => resolve(false));
    // Omit host so the probe matches Next.js (often `::`), avoiding false "free" on :: vs 127.0.0.1.
    s.listen(port, () => {
      s.close(() => resolve(true));
    });
  });
}

const projectRoot = resolveProjectRoot();
const meta = await waitDaemonMeta(projectRoot);

const envPath = join(pkgRoot, ".env.development.local");
if (meta?.httpOrigin && meta?.wsUrl) {
  writeFileSync(
    envPath,
    `# generated by dev.mjs — do not commit if you prefer\nNEXT_PUBLIC_DAEMON_HTTP=${meta.httpOrigin}\nNEXT_PUBLIC_DAEMON_WS=${meta.wsUrl}\n`,
    "utf8",
  );
  console.log(`[DevDeck] Synced daemon from ${join(projectRoot, ".devdeck", "daemon.json")}`);
} else {
  console.warn("[DevDeck] No .devdeck/daemon.json yet — using default daemon URLs (start daemon first or set NEXT_PUBLIC_*)");
}

const base = Number(process.env.DEVDECK_UI_PORT ?? 4321);
let port = base;
for (; port < base + 40; port++) {
  if (await portFree(port)) break;
}
if (port >= base + 40) {
  console.error("[DevDeck] No free port for UI in range", base, "..", base + 39);
  process.exit(1);
}

if (port !== 4321) {
  console.warn(`[DevDeck] Port ${base} busy → using http://127.0.0.1:${port}`);
} else {
  console.log(`[DevDeck] UI http://127.0.0.1:${port}`);
}

const nextBin = join(pkgRoot, "node_modules", "next", "dist", "bin", "next");

const child = spawn(process.execPath, [nextBin, "dev", "-p", String(port)], {
  cwd: pkgRoot,
  stdio: "inherit",
  windowsHide: true,
});

child.on("exit", (code, signal) => {
  if (signal) process.kill(process.pid, signal);
  process.exit(code ?? 1);
});
